// <auto-generated />
using AnyJob.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnyJob.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220212214947_Seed")]
    partial class Seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AnyJob.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Software development"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Quality Assurance /Control"
                        },
                        new
                        {
                            Id = 3,
                            Name = "UI/UX/Graphic Design"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Product/Project Management"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sales/service management"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Marketing/Advertising"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Finance Management"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Healthcare/Pharmaceutical"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Human Resources"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Production"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Business/Management"
                        },
                        new
                        {
                            Id = 12,
                            Name = "IT security/Networks"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Insurance"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Data Science/Data Engineering"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Foreign language"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Economics"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Hardware Design / Engineering"
                        },
                        new
                        {
                            Id = 18,
                            Name = "System Admin/Engineer"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Content writing"
                        },
                        new
                        {
                            Id = 20,
                            Name = "DevOps/Infrastructure"
                        });
                });

            modelBuilder.Entity("AnyJob.Domain.EmploymentType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmploymentTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Full Time"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Part Time"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Contractor"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Intern"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Seasonal / Temp"
                        });
                });

            modelBuilder.Entity("AnyJob.Domain.JobPosting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("EmploymentTypeId")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("EmploymentTypeId");

                    b.HasIndex("LocationId");

                    b.ToTable("JobPostings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 14,
                            EmploymentTypeId = 5,
                            LocationId = 11,
                            Title = "VP Product Management"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 19,
                            EmploymentTypeId = 1,
                            LocationId = 10,
                            Title = "Analog Circuit Design manager"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 7,
                            EmploymentTypeId = 5,
                            LocationId = 18,
                            Title = "GIS Technical Architect"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 19,
                            EmploymentTypeId = 2,
                            LocationId = 21,
                            Title = "Nurse Practicioner"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 9,
                            EmploymentTypeId = 3,
                            LocationId = 24,
                            Title = "Assistant Professor"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 20,
                            EmploymentTypeId = 4,
                            LocationId = 23,
                            Title = "Systems Administrator II"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 11,
                            EmploymentTypeId = 3,
                            LocationId = 5,
                            Title = "Graphic Designer"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 19,
                            EmploymentTypeId = 1,
                            LocationId = 13,
                            Title = "Web Developer IV"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 9,
                            EmploymentTypeId = 2,
                            LocationId = 28,
                            Title = "VP Accounting"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 8,
                            EmploymentTypeId = 2,
                            LocationId = 18,
                            Title = "Geological Engineer"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 9,
                            EmploymentTypeId = 4,
                            LocationId = 29,
                            Title = "Information Systems Manager"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 11,
                            EmploymentTypeId = 1,
                            LocationId = 13,
                            Title = "Software Test Engineer III"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 11,
                            EmploymentTypeId = 2,
                            LocationId = 11,
                            Title = "Technical Writer"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 7,
                            EmploymentTypeId = 4,
                            LocationId = 20,
                            Title = "Geological Engineer"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 16,
                            EmploymentTypeId = 1,
                            LocationId = 12,
                            Title = "Programmer I"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 4,
                            EmploymentTypeId = 5,
                            LocationId = 35,
                            Title = "Food Chemist"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 3,
                            EmploymentTypeId = 5,
                            LocationId = 38,
                            Title = "Systems Administrator IV"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 3,
                            EmploymentTypeId = 5,
                            LocationId = 34,
                            Title = "Business Systems Development Analyst"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 19,
                            EmploymentTypeId = 4,
                            LocationId = 19,
                            Title = "Business Systems Development Analyst"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 12,
                            EmploymentTypeId = 3,
                            LocationId = 32,
                            Title = "Junior Executive"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 9,
                            EmploymentTypeId = 1,
                            LocationId = 17,
                            Title = "Senior Sales Associate"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 9,
                            EmploymentTypeId = 1,
                            LocationId = 37,
                            Title = "Research Assistant I"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 3,
                            EmploymentTypeId = 3,
                            LocationId = 1,
                            Title = "Compensation Analyst"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 18,
                            EmploymentTypeId = 2,
                            LocationId = 30,
                            Title = "Media Manager I"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 3,
                            EmploymentTypeId = 2,
                            LocationId = 24,
                            Title = "Physical Therapy Assistant"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 10,
                            EmploymentTypeId = 5,
                            LocationId = 37,
                            Title = "Paralegal"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 8,
                            EmploymentTypeId = 3,
                            LocationId = 38,
                            Title = "Safety Technician I"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 2,
                            EmploymentTypeId = 1,
                            LocationId = 33,
                            Title = "Teacher"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 2,
                            EmploymentTypeId = 5,
                            LocationId = 23,
                            Title = "VP Sales"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 13,
                            EmploymentTypeId = 5,
                            LocationId = 30,
                            Title = "Clinical Specialist"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 20,
                            EmploymentTypeId = 1,
                            LocationId = 37,
                            Title = "Food Chemist"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 17,
                            EmploymentTypeId = 3,
                            LocationId = 23,
                            Title = "Associate Professor"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 20,
                            EmploymentTypeId = 1,
                            LocationId = 10,
                            Title = "Developer II"
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 13,
                            EmploymentTypeId = 2,
                            LocationId = 10,
                            Title = "Data Coordiator"
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 5,
                            EmploymentTypeId = 2,
                            LocationId = 25,
                            Title = "Health Coach IV"
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 4,
                            EmploymentTypeId = 2,
                            LocationId = 11,
                            Title = "Staff Scientist"
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 8,
                            EmploymentTypeId = 5,
                            LocationId = 10,
                            Title = "Social Worker"
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 10,
                            EmploymentTypeId = 3,
                            LocationId = 28,
                            Title = "Financial Advisor"
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 5,
                            EmploymentTypeId = 2,
                            LocationId = 13,
                            Title = "Database Administrator II"
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 13,
                            EmploymentTypeId = 5,
                            LocationId = 13,
                            Title = "VP Sales"
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 8,
                            EmploymentTypeId = 3,
                            LocationId = 2,
                            Title = "Software Consultant"
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 9,
                            EmploymentTypeId = 2,
                            LocationId = 34,
                            Title = "Database Administrator II"
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 19,
                            EmploymentTypeId = 2,
                            LocationId = 36,
                            Title = "Office Assistant III"
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 7,
                            EmploymentTypeId = 4,
                            LocationId = 16,
                            Title = "Paralegal"
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 2,
                            EmploymentTypeId = 5,
                            LocationId = 32,
                            Title = "Database Administrator II"
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 10,
                            EmploymentTypeId = 1,
                            LocationId = 34,
                            Title = "Food Chemist"
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 13,
                            EmploymentTypeId = 5,
                            LocationId = 27,
                            Title = "Computer Systems Analyst III"
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 20,
                            EmploymentTypeId = 5,
                            LocationId = 17,
                            Title = "Assistant Professor"
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 19,
                            EmploymentTypeId = 3,
                            LocationId = 24,
                            Title = "Technical Writer"
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 12,
                            EmploymentTypeId = 1,
                            LocationId = 33,
                            Title = "Help Desk Technician"
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 12,
                            EmploymentTypeId = 1,
                            LocationId = 28,
                            Title = "Cost Accountant"
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 8,
                            EmploymentTypeId = 4,
                            LocationId = 14,
                            Title = "Health Coach I"
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 6,
                            EmploymentTypeId = 1,
                            LocationId = 10,
                            Title = "Executive Secretary"
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 10,
                            EmploymentTypeId = 3,
                            LocationId = 2,
                            Title = "Analog Circuit Design manager"
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 17,
                            EmploymentTypeId = 3,
                            LocationId = 9,
                            Title = "Dental Hygienist"
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 9,
                            EmploymentTypeId = 2,
                            LocationId = 10,
                            Title = "Design Engineer"
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 7,
                            EmploymentTypeId = 5,
                            LocationId = 29,
                            Title = "Health Coach III"
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 13,
                            EmploymentTypeId = 5,
                            LocationId = 14,
                            Title = "Speech Pathologist"
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 1,
                            EmploymentTypeId = 4,
                            LocationId = 22,
                            Title = "Research Associate"
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 18,
                            EmploymentTypeId = 2,
                            LocationId = 2,
                            Title = "VP Quality Control"
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 7,
                            EmploymentTypeId = 5,
                            LocationId = 11,
                            Title = "Executive Secretary"
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 2,
                            EmploymentTypeId = 2,
                            LocationId = 11,
                            Title = "Internal Auditor"
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 16,
                            EmploymentTypeId = 4,
                            LocationId = 32,
                            Title = "Biostatistician II"
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 5,
                            EmploymentTypeId = 1,
                            LocationId = 19,
                            Title = "Internal Auditor"
                        },
                        new
                        {
                            Id = 65,
                            CategoryId = 2,
                            EmploymentTypeId = 2,
                            LocationId = 37,
                            Title = "Senior Financial Analyst"
                        },
                        new
                        {
                            Id = 66,
                            CategoryId = 1,
                            EmploymentTypeId = 2,
                            LocationId = 1,
                            Title = "Internal Auditor"
                        },
                        new
                        {
                            Id = 67,
                            CategoryId = 4,
                            EmploymentTypeId = 1,
                            LocationId = 27,
                            Title = "Senior Cost Accountant"
                        },
                        new
                        {
                            Id = 68,
                            CategoryId = 10,
                            EmploymentTypeId = 2,
                            LocationId = 37,
                            Title = "Geological Engineer"
                        },
                        new
                        {
                            Id = 69,
                            CategoryId = 9,
                            EmploymentTypeId = 2,
                            LocationId = 30,
                            Title = "Administrative Assistant IV"
                        },
                        new
                        {
                            Id = 70,
                            CategoryId = 11,
                            EmploymentTypeId = 2,
                            LocationId = 27,
                            Title = "Research Assistant III"
                        },
                        new
                        {
                            Id = 71,
                            CategoryId = 13,
                            EmploymentTypeId = 4,
                            LocationId = 26,
                            Title = "Account Executive"
                        },
                        new
                        {
                            Id = 72,
                            CategoryId = 17,
                            EmploymentTypeId = 3,
                            LocationId = 12,
                            Title = "Account Executive"
                        },
                        new
                        {
                            Id = 73,
                            CategoryId = 3,
                            EmploymentTypeId = 2,
                            LocationId = 39,
                            Title = "Senior Quality Engineer"
                        },
                        new
                        {
                            Id = 74,
                            CategoryId = 11,
                            EmploymentTypeId = 2,
                            LocationId = 27,
                            Title = "Social Worker"
                        },
                        new
                        {
                            Id = 75,
                            CategoryId = 18,
                            EmploymentTypeId = 5,
                            LocationId = 40,
                            Title = "Nurse"
                        },
                        new
                        {
                            Id = 76,
                            CategoryId = 4,
                            EmploymentTypeId = 1,
                            LocationId = 15,
                            Title = "Web Designer II"
                        },
                        new
                        {
                            Id = 77,
                            CategoryId = 8,
                            EmploymentTypeId = 2,
                            LocationId = 37,
                            Title = "Database Administrator II"
                        },
                        new
                        {
                            Id = 78,
                            CategoryId = 12,
                            EmploymentTypeId = 1,
                            LocationId = 26,
                            Title = "Electrical Engineer"
                        },
                        new
                        {
                            Id = 79,
                            CategoryId = 17,
                            EmploymentTypeId = 5,
                            LocationId = 7,
                            Title = "Quality Engineer"
                        },
                        new
                        {
                            Id = 80,
                            CategoryId = 3,
                            EmploymentTypeId = 3,
                            LocationId = 1,
                            Title = "Geological Engineer"
                        },
                        new
                        {
                            Id = 81,
                            CategoryId = 5,
                            EmploymentTypeId = 5,
                            LocationId = 13,
                            Title = "Cost Accountant"
                        },
                        new
                        {
                            Id = 82,
                            CategoryId = 17,
                            EmploymentTypeId = 4,
                            LocationId = 11,
                            Title = "Geologist I"
                        },
                        new
                        {
                            Id = 83,
                            CategoryId = 7,
                            EmploymentTypeId = 1,
                            LocationId = 34,
                            Title = "Structural Analysis Engineer"
                        },
                        new
                        {
                            Id = 84,
                            CategoryId = 7,
                            EmploymentTypeId = 5,
                            LocationId = 5,
                            Title = "Biostatistician I"
                        },
                        new
                        {
                            Id = 85,
                            CategoryId = 2,
                            EmploymentTypeId = 1,
                            LocationId = 3,
                            Title = "Physical Therapy Assistant"
                        },
                        new
                        {
                            Id = 86,
                            CategoryId = 13,
                            EmploymentTypeId = 1,
                            LocationId = 33,
                            Title = "Environmental Tech"
                        },
                        new
                        {
                            Id = 87,
                            CategoryId = 10,
                            EmploymentTypeId = 3,
                            LocationId = 6,
                            Title = "Assistant Professor"
                        },
                        new
                        {
                            Id = 88,
                            CategoryId = 19,
                            EmploymentTypeId = 2,
                            LocationId = 35,
                            Title = "Accounting Assistant I"
                        },
                        new
                        {
                            Id = 89,
                            CategoryId = 17,
                            EmploymentTypeId = 2,
                            LocationId = 31,
                            Title = "Analog Circuit Design manager"
                        },
                        new
                        {
                            Id = 90,
                            CategoryId = 12,
                            EmploymentTypeId = 1,
                            LocationId = 16,
                            Title = "Nuclear Power Engineer"
                        },
                        new
                        {
                            Id = 91,
                            CategoryId = 3,
                            EmploymentTypeId = 2,
                            LocationId = 24,
                            Title = "Analog Circuit Design manager"
                        },
                        new
                        {
                            Id = 92,
                            CategoryId = 16,
                            EmploymentTypeId = 4,
                            LocationId = 12,
                            Title = "Community Outreach Specialist"
                        },
                        new
                        {
                            Id = 93,
                            CategoryId = 20,
                            EmploymentTypeId = 3,
                            LocationId = 32,
                            Title = "Environmental Specialist"
                        },
                        new
                        {
                            Id = 94,
                            CategoryId = 19,
                            EmploymentTypeId = 4,
                            LocationId = 12,
                            Title = "Desktop Support Technician"
                        },
                        new
                        {
                            Id = 95,
                            CategoryId = 5,
                            EmploymentTypeId = 2,
                            LocationId = 37,
                            Title = "Financial Advisor"
                        },
                        new
                        {
                            Id = 96,
                            CategoryId = 12,
                            EmploymentTypeId = 4,
                            LocationId = 4,
                            Title = "Graphic Designer"
                        },
                        new
                        {
                            Id = 97,
                            CategoryId = 13,
                            EmploymentTypeId = 4,
                            LocationId = 7,
                            Title = "Occupational Therapist"
                        },
                        new
                        {
                            Id = 98,
                            CategoryId = 18,
                            EmploymentTypeId = 2,
                            LocationId = 14,
                            Title = "Research Associate"
                        },
                        new
                        {
                            Id = 99,
                            CategoryId = 10,
                            EmploymentTypeId = 5,
                            LocationId = 28,
                            Title = "Chief Design Engineer"
                        },
                        new
                        {
                            Id = 100,
                            CategoryId = 17,
                            EmploymentTypeId = 1,
                            LocationId = 26,
                            Title = "Systems Administrator II"
                        });
                });

            modelBuilder.Entity("AnyJob.Domain.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Locations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Yerevan",
                            Country = "Armenia"
                        },
                        new
                        {
                            Id = 2,
                            City = "Baltimore",
                            Country = "United States",
                            State = "Maryland"
                        },
                        new
                        {
                            Id = 3,
                            City = "Tsaghkaber",
                            Country = "Armenia"
                        },
                        new
                        {
                            Id = 4,
                            City = "Whitwell",
                            Country = "United Kingdom",
                            State = "England"
                        },
                        new
                        {
                            Id = 5,
                            City = "Dortmund",
                            Country = "Germany",
                            State = "Nordrhein-Westfalen"
                        },
                        new
                        {
                            Id = 6,
                            City = "Wuppertal",
                            Country = "Germany",
                            State = "Nordrhein-Westfalen"
                        },
                        new
                        {
                            Id = 7,
                            City = "San Antonio",
                            Country = "United States"
                        },
                        new
                        {
                            Id = 8,
                            City = "Sydney Mines",
                            Country = "Canada"
                        },
                        new
                        {
                            Id = 9,
                            City = "North Battleford",
                            Country = "Canada"
                        },
                        new
                        {
                            Id = 10,
                            City = "Fermont",
                            Country = "Canada",
                            State = "Quebec"
                        },
                        new
                        {
                            Id = 11,
                            City = "Archis",
                            Country = "Armenia"
                        },
                        new
                        {
                            Id = 12,
                            City = "Abovyan",
                            Country = "Armenia"
                        },
                        new
                        {
                            Id = 13,
                            City = "Bagratashen",
                            Country = "Armenia"
                        },
                        new
                        {
                            Id = 14,
                            City = "Aurora",
                            Country = "United States",
                            State = "Colorado"
                        },
                        new
                        {
                            Id = 15,
                            City = "Las Vegas",
                            Country = "United States",
                            State = "Nevada"
                        },
                        new
                        {
                            Id = 16,
                            City = "San Antonio",
                            Country = "United States",
                            State = "Texas"
                        },
                        new
                        {
                            Id = 17,
                            City = "Valencia",
                            Country = "Spain",
                            State = "Comunidad Valenciana"
                        },
                        new
                        {
                            Id = 18,
                            City = "Thessalon",
                            Country = "Canada",
                            State = "Ontario"
                        },
                        new
                        {
                            Id = 19,
                            City = "Logrono",
                            Country = "Spain",
                            State = "La Rioja"
                        },
                        new
                        {
                            Id = 20,
                            City = "Buffalo",
                            Country = "United States",
                            State = "New York"
                        },
                        new
                        {
                            Id = 21,
                            City = "Summerland",
                            Country = "Canada",
                            State = "British Columbia"
                        },
                        new
                        {
                            Id = 22,
                            City = "Zamora",
                            Country = "Spain",
                            State = "Castilla - Leon"
                        },
                        new
                        {
                            Id = 23,
                            City = "Labrador City",
                            Country = "Canada",
                            State = "Newfoundland and Labrador"
                        },
                        new
                        {
                            Id = 24,
                            City = "Bassano",
                            Country = "Canada",
                            State = "Alberta"
                        },
                        new
                        {
                            Id = 25,
                            City = "Ceuta",
                            Country = "Spain",
                            State = "Ceuta"
                        },
                        new
                        {
                            Id = 26,
                            City = "Atlanta",
                            Country = "United States"
                        },
                        new
                        {
                            Id = 27,
                            City = "Stuttgart",
                            Country = "Germany",
                            State = "Baden-Württemberg"
                        },
                        new
                        {
                            Id = 28,
                            City = "Hannover",
                            Country = "Germany",
                            State = "Niedersachsen"
                        },
                        new
                        {
                            Id = 29,
                            City = "Harbour Breton",
                            Country = "Canada",
                            State = "Newfoundland and Labrador"
                        },
                        new
                        {
                            Id = 30,
                            City = "Alexandria",
                            Country = "United States",
                            State = "Virginia"
                        },
                        new
                        {
                            Id = 31,
                            City = "New Orleans",
                            Country = "United States",
                            State = "Louisiana"
                        },
                        new
                        {
                            Id = 32,
                            City = "Akunk’",
                            Country = "Armenia"
                        },
                        new
                        {
                            Id = 33,
                            City = "Gagarin",
                            Country = "Armenia"
                        },
                        new
                        {
                            Id = 34,
                            City = "Windsor",
                            Country = "Canada",
                            State = "Quebec"
                        },
                        new
                        {
                            Id = 35,
                            City = "Bartsrashen",
                            Country = "Armenia"
                        },
                        new
                        {
                            Id = 36,
                            City = "Santander",
                            Country = "Spain"
                        },
                        new
                        {
                            Id = 37,
                            City = "Perth",
                            Country = "Australia",
                            State = "Western Australia"
                        },
                        new
                        {
                            Id = 38,
                            City = "Orlando",
                            Country = "United States",
                            State = "Florida"
                        },
                        new
                        {
                            Id = 39,
                            City = "Munchen",
                            Country = "Germany",
                            State = "Bayern"
                        },
                        new
                        {
                            Id = 40,
                            City = "Solingen",
                            Country = "Germany",
                            State = "Nordrhein-Westfalen"
                        });
                });

            modelBuilder.Entity("AnyJob.Domain.JobPosting", b =>
                {
                    b.HasOne("AnyJob.Domain.Category", "Category")
                        .WithMany("JobPostings")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnyJob.Domain.EmploymentType", "EmploymentType")
                        .WithMany("JobPostings")
                        .HasForeignKey("EmploymentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnyJob.Domain.Location", "Location")
                        .WithMany("JobPostings")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("EmploymentType");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("AnyJob.Domain.Category", b =>
                {
                    b.Navigation("JobPostings");
                });

            modelBuilder.Entity("AnyJob.Domain.EmploymentType", b =>
                {
                    b.Navigation("JobPostings");
                });

            modelBuilder.Entity("AnyJob.Domain.Location", b =>
                {
                    b.Navigation("JobPostings");
                });
#pragma warning restore 612, 618
        }
    }
}
